export const ADDUSERTOSTORE = 'STORE.ADDUSER';
export const ADDPRODUCTTOSTORE = 'STORE.ADDPRODUCT';
export const ADDTOCART = 'STORE.ADDTOCART';
export const SHOWCART = 'STORE.SHOWCART';
export const DISPLAYALLPRODUCTS = 'STORE.DISPLAYPRODUCT';
export const REMOVESELECTEDPRODUCT = 'STORE.REMOVESELECTEDPRODUCT';
export const SELECTPRODUCT = 'STORE.SELECTPRODUCT';
